### ISSUE TITLE
Requirements file is missing packages

### ISSUE THREAD

**Issue by shehzadashiq** [touhid314/Coursera-Downloader#3]
In the V2 branch the requirements file needs to be updated.

The following packages need to be added to allow the utility to run.

```sh
pillow
backoff
```

If these packages are not installed the following error are generated e.g. if backoff is not installed

```sh
Exception in Tkinter callback
Traceback (most recent call last):
ModuleNotFoundError: No module named 'backoff'
```

**Comment by touhid314** [comment]
added
